- block:
  - name: try running supervisorctl
    shell: supervisorctl >/dev/null 2>&1
    register: supervisorctl_call_return
    when: supervisord_run_supervisorctl

  - name: create directory for supervisor log
    file:
      state: directory
      recurse: yes
      path: "{{ item }}"
    when: supervisord_app_log_directories | length > 0
    with_items: "{{ supervisord_app_log_directories }}"

  - name: Disable supervisor because service start doesn't read env vars
    service:
      name: supervisor
      enabled: false
    when: supervisord_service_disable

  become: true
  become_method: sudo
